#!/usr/bin/env node
/**
 * Single source of truth: src/styles/tokens.json, exported from the Get Invites
 * design system. This emits two artefacts and nothing else edits them:
 *
 *   src/styles/tokens.css   CSS custom properties + type-style classes
 *   tailwind.tokens.json    the same scale, shaped for tailwind.config.ts
 *
 * Runs on predev and prebuild, so the code can never drift from the system.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(fs.readFileSync(path.join(root, 'src/styles/tokens.json'), 'utf8'));

/** "{marigold-500}" -> "var(--marigold-500)" */
const deref = (v) =>
  typeof v === 'string' && v.startsWith('{') && v.endsWith('}') ? `var(--${v.slice(1, -1)})` : v;

const themes = tokens.color.themes.map((t) => t.id);
const firstTheme = themes[0];

const valueFor = (token, theme) => {
  const v = token.value;
  if (typeof v === 'string') return deref(v);
  return deref(v[theme] ?? v[firstTheme]);
};

/** Families shaped {tokens:[{name,value}]} that are not theme-aware. */
const flatFamilies = ['spacing', 'radius', 'zIndex'];

function themedBlock(theme) {
  const lines = [];
  for (const t of tokens.color.tokens) lines.push(`  --${t.name}: ${valueFor(t, theme)};`);
  if (tokens.shadow) for (const t of tokens.shadow.tokens) lines.push(`  --${t.name}: ${valueFor(t, theme)};`);
  return lines.join('\n');
}

/** A font family entry is either a plain string (same in every theme) or a
 * theme-keyed object shaped just like a color token's value. */
const familyFor = (stack, theme) =>
  typeof stack === 'string' ? stack : stack[theme] ?? stack[firstTheme];

/** Only the tokens whose value actually differs from the first theme. */
function themedOverrides(theme) {
  const lines = [];
  const diff = (t) => valueFor(t, theme) !== valueFor(t, firstTheme);
  for (const t of tokens.color.tokens) if (diff(t)) lines.push(`    --${t.name}: ${valueFor(t, theme)};`);
  if (tokens.shadow) for (const t of tokens.shadow.tokens) if (diff(t)) lines.push(`    --${t.name}: ${valueFor(t, theme)};`);
  for (const [key, stack] of Object.entries(tokens.type.families))
    if (familyFor(stack, theme) !== familyFor(stack, firstTheme))
      lines.push(`    --font-${key}: ${familyFor(stack, theme)};`);
  return lines.join('\n');
}

function staticBlock() {
  const lines = [];
  for (const fam of flatFamilies) {
    if (!tokens[fam]) continue;
    for (const t of tokens[fam].tokens) lines.push(`  --${t.name}: ${t.value};`);
  }
  for (const [key, stack] of Object.entries(tokens.type.families))
    lines.push(`  --font-${key}: ${familyFor(stack, firstTheme)};`);
  return lines.join('\n');
}

function typeClasses() {
  const out = [];
  for (const group of tokens.type.groups) {
    for (const s of group.styles) {
      const family = s.family ?? group.family;
      const decls = [`  font-family: var(--font-${family});`, `  font-size: ${s.fontSize};`];
      if (s.lineHeight) decls.push(`  line-height: ${s.lineHeight};`);
      if (s.fontWeight) decls.push(`  font-weight: ${s.fontWeight};`);
      if (s.letterSpacing) decls.push(`  letter-spacing: ${s.letterSpacing};`);
      if (s.fontStyle) decls.push(`  font-style: ${s.fontStyle};`);
      out.push(`.${s.name} {\n${decls.join('\n')}\n}`);
    }
  }
  return out.join('\n\n');
}

// Every theme past the first gets an explicit `[data-theme]` selector. Only
// "dark" is also a real `prefers-color-scheme` value, so it alone gets the
// OS-preference media query too — extra named themes (e.g. "regal") are
// opt-in only, picked with the explicit attribute, never by OS default.
const extraThemes = themes.slice(1);
const OS_MEDIA_THEMES = new Set(['dark', 'light']);

const css = `/* GENERATED by scripts/build-tokens.mjs from src/styles/tokens.json. Do not edit. */

:root {
${themedBlock(firstTheme)}
${staticBlock()}
}

${extraThemes
  .map((theme) => {
    const explicitBlock = `:root[data-theme="${theme}"] {
  color-scheme: ${OS_MEDIA_THEMES.has(theme) ? theme : 'normal'};
${themedOverrides(theme)}
}`;
    if (!OS_MEDIA_THEMES.has(theme)) return explicitBlock;
    return `@media (prefers-color-scheme: ${theme}) {
  :root:not([data-theme="light"]) {
    color-scheme: ${theme};
${themedOverrides(theme)}
  }
}

${explicitBlock}`;
  })
  .join('\n\n')}

${typeClasses()}
`;

fs.writeFileSync(path.join(root, 'src/styles/tokens.css'), css);

/* ---- Tailwind theme ------------------------------------------------- */
const asVars = (list) => Object.fromEntries(list.map((t) => [t.name, `var(--${t.name})`]));
const strip = (prefix, list) =>
  Object.fromEntries(list.map((t) => [t.name.replace(prefix, ''), `var(--${t.name})`]));

const fontSize = {};
for (const group of tokens.type.groups) {
  for (const s of group.styles) {
    fontSize[s.name] = [s.fontSize, { lineHeight: String(s.lineHeight ?? 'normal'), letterSpacing: s.letterSpacing, fontWeight: String(s.fontWeight ?? 400) }];
  }
}

const theme = {
  colors: asVars(tokens.color.tokens),
  spacing: strip('space-', tokens.spacing.tokens),
  borderRadius: strip('radius-', tokens.radius.tokens),
  boxShadow: strip('shadow-', tokens.shadow.tokens),
  zIndex: strip('z-', tokens.zIndex.tokens),
  fontFamily: Object.fromEntries(Object.keys(tokens.type.families).map((k) => [k, `var(--font-${k})`])),
  fontSize,
};

fs.writeFileSync(path.join(root, 'tailwind.tokens.json'), JSON.stringify(theme, null, 2));

const n = tokens.color.tokens.length;
const styles = tokens.type.groups.reduce((a, g) => a + g.styles.length, 0);
console.log(`tokens: ${n} colours x ${themes.length} themes, ${styles} type styles -> tokens.css + tailwind.tokens.json`);
